name: "AppBrickie"
description: "To Test and Build a Debug Android App"
author: "hkpdev008@gmail.com"

inputs:
  chatid:
    description: "The Place to send the App"
    requried: true
  packagename:
    description: "Name of your app"
    requried: false
  type:
    description: "The Framework that you are using to build your app"
    requried: true
    default: "native"
  abi:
    description: "Target ABI for flutter builds"
    requried: false
  firebase:
    description: "Contents of your google-services.json file"
    requried: false
  keystore:
    description: "The text dump you generated of your keystore"
    requried: false
  keystorePassword:
    description: "Password of your keystore file"
    requried: false
  keyAlias:
    description: "Key alias of your key that needs to be signed"
    requried: false
  keyPassword: 
    description: "Password of the key in your keystore file"
    requried: false
outputs:
  result:
    description: "Result of automated send"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.chatid}}

branding:
  icon: "play-circle"
  color: "gray-dark"
