name: "AppBrickie"
description: "To Test and Build a Debug Android App"
author: "hkpdev008@gmail.com"

inputs:
  chatid:
    description: "The Place to send the App"
    requried: true
  packagename:
    description: "Name of your app"
    requried: false
  type:
    description: "The Framework that you are using to build your app"
    requried: true
    default: "native"

outputs:
  result:
    description: "Result of automated send"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.chatid}}

branding:
  icon: "play-circle"
  color: "gray-dark"
