name: "AppBrickie"
description: "To Test and Build a Debug Android App"
author: "hkpdev008@gmail.com"

runs:
    using: "docker"
    image: "Dockerfile"
branding:
  icon: "play-circle"
  color: "gray-dark"
